name: Deploy to GH Pages
on:
  push:
    branches: [osumd-workflow-testing]
jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
    with:
      upload-pages-artifact: true
  deploy-to-pages:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    envrionment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/configure-pages@v3
      - uses: actions/deploy-pages@v2
        id: deployment