name: Deploy to GH Pages
on: [push,pull_request]
jobs:
  build-and-save-artifact:
    uses: ./.github/workflows/build_on_push_artifact.yml
  deploy-to-pages:
    runs-on: ubuntu-latest
    needs: build-and-save-artifact
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/configure-pages@v3
      - uses: actions/deploy-pages@v2
        id: deployment