name: build-and-serve
on: [workflow_call]
jobs:
  build-and-serve:
    runs-on: ubuntu-latest
    env:
      API_PORT: 8080
    steps:
      - uses : actions/checkout@v3
      - uses : actions/setup-node@v3
        with:
            node-version: 20
      - run : npm ci
      - uses: JarvusInnovations/background-action@v1.0.5
        name: Webpack Server Localhost Background Process
        with: 
          run : npm run start
          wait-on: http://localhost:${{ env.API_PORT }}
